change step status

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -60,23 +60,35 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
 
-      - name: Run Tests
+      - name: Run Tests and Capture Logs
         run: |
-          ./gradlew test --info 
-
-      - name: Send Slack notification on test result
-        run: |
-          if [ $? -eq 0 ]; then
-            STATUS="Tests passed!"
+          # Run the tests and capture the output in a log file
+          ./gradlew test --info > build/test-logs/test.log 2>&1 || true  # Capture both stdout and stderr
+          
+          # Search the log for "BUILD FAILED" to determine test status
+          if grep -q "BUILD FAILED" build/test-logs/test.log; then
+            echo "test_status=failed" >> $GITHUB_ENV  # Set failure flag for subsequent steps
           else
-            STATUS="Tests failed! Please check the details in the workflow logs."
+            echo "test_status=passed" >> $GITHUB_ENV  # Set success flag for subsequent steps
           fi
+          continue-on-error: true  # Allow workflow to continue even if the tests fail
+
+      - name: Send Slack notification on test result (failure or success)
+        run: |
+          if [ "$test_status" == "failed" ]; then
+            STATUS="Tests failed! Please check the details in the workflow logs."
+          else
+            STATUS="Tests passed!"
+          fi
+          
+            # Send the Slack notification
           curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${STATUS}\"}" ${{ secrets.SLACK_WEBHOOK }}
-        if: always()
+        if: always()  # Ensure this step runs even if the previous step failed
 
 
       - name: Generate Allure report
         run: ./gradlew allureReport
+        if: always()
 
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
@@ -84,6 +96,7 @@ jobs:
           name: allure-report
           path: build/reports/allure-report/allureReport
           overwrite: true
+        if: always()
 
       - name: Publish Test Results
         uses: EnricoMi/publish-unit-test-result-action@v2
